# Generated by Django 5.1.2 on 2024-10-17 00:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='movies', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])]),
        ),
    ]
